name: Build and Test

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    #- name: Login to DockerHub
    #  uses: docker/login-action@v1
    #  with:
    #    username: ${{ secrets.DOCKERHUB_USERNAME }}
    #    password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: your-dockerhub-username/your-image-name:latest

    - name: Test Application
      run: |
        docker run -d --name test_container -p 4840:4840 your-dockerhub-username/your-image-name:latest
        sleep 10 # Adjust this sleep time according to your application's startup time
        # Here you should include any commands necessary to test your application
        # For example:
        curl -v localhost:4840
        docker stop test_container
